version: '2'
services:
  boinc:
    restart: always
    image: akira345/boinc:latest
    volumes:
      - "boinc_data:/data:rw"
    environment:
      PROJECT_URL: 
      AUTH_KEY: 
volumes:
  boinc_data:
    driver: local
