version: "2"
services:
  boinc:
    restart: always
    image: akira345/boinc:account_manager
    volumes:
      - "boinc_data:/data:rw"
    environment:
      BOINC_GUI_RPC_PASSWORD: "123"
      BOINC_REMOTE_HOST: "127.0.0.1"
      BOINC_CMD_LINE_OPTIONS: ""
volumes:
  boinc_data:
    driver: local
