version: "2"
services:
  boinc:
    restart: always
    image: akira345/boinc:account_manager
    volumes:
      - "boinc_data:/data:rw"
    environment:
      BOINC_GUI_RPC_PASSWORD: "123"
      BOINC_CMD_LINE_OPTIONS: "--allow_remote_gui_rpc"
    ports:
      - "31416:31416"
volumes:
  boinc_data:
    driver: local
